version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    image: tp2-gl4-devops
    container_name: tp2-gl4-devops-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      BACKEND_PORT: "8000"
      BASE_FOTMOB_API: "https://www.fotmob.com/api"
      NODE_ENV: "production"
      NODE_VERSION: "20"
      SEARCH_FOTMOB_API: "https://apigw.fotmob.com/searchapi"
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "root"
      MONGO_HOST: "db"
      MONGO_URI: "mongodb://db/db"

volumes:
  mongodb_data: {}
